#all: broadcast-example unicast-sender unicast-receiver  #default: not working srec cat problem
all: broadcast-example.bin unicast-sender.bin unicast-receiver.bin

APPS=servreg-hack
CONTIKI=../../..

CONTIKI_WITH_IPV6 = 1
include $(CONTIKI)/Makefile.include
